[versions]
kotlin = "2.3.0"
testballoon = "0.8.0-K2.3.0"
agp = "8.12.3"
asp = "20251023"
kotest = "6.0.4"
modulator = "0.1.0"

[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }
agp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
testballoon = { id = "de.infix.testBalloon", version.ref = "testballoon" }
modulator = { id = "at.asitplus.gradle.modulator", version.ref = "modulator" }